version: '2'
services:
  cassandra-service:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - cassandra-data:/var/lib/cassandra

  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    depends_on:
      cassandra-service:
        condition: service_healthy
    volumes:
      - ./src/main/scala/infrastructure/docker/ddl-scripts:/scripts
      - ./init/init-cassandra.sh:/app/init-cassandra.sh
    entrypoint: ["/bin/bash", "/app/init-cassandra.sh"]
    environment:
      - CASSANDRA_HOST=cassandra-service

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "/app/create-topics.sh"]
    volumes:
      - ./init/create-topics.sh:/app/create-topics.sh
      
  sentiment-analysis:
    build: sentiment_analysis/.
    container_name: sentiment-analysis
    depends_on:
      cassandra-service:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CASSANDRA_HOST: cassandra-service
      CASSANDRA_PORT: 9042
    volumes:
      - ./models:/root/.cache/huggingface/hub

volumes:
  cassandra-data: